name: ROS2 CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  test_environment:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        ros_distribution: [humble]

        include:
          - ros_distribution: humble
            docker_image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-ros-base-latest

    container:
      image: ${{ matrix.docker_image }}

    steps:
      - run: mkdir tmp_ws

      - uses: actions/checkout@v4
        with:
          path: tmp_ws

      # Note that action-ros-ci will rm -rf ros_ws
      - uses: ros-tooling/action-ros-ci@0.4.2
        with:
          package-name: |
            orca_base
            orca_bringup
            orca_description
            orca_msgs
            orca_nav2
            orca_shared
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: tmp_ws/workspace.repos
